# Generated by Django 4.1.2 on 2023-01-25 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='会社名')),
                ('zip', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, max_length=13, null=True, verbose_name='FAX')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('representative', models.CharField(max_length=10, verbose_name='代表者名')),
                ('established', models.DateField(verbose_name='設立日')),
                ('business_content', models.TextField(verbose_name='事業内容')),
                ('capital', models.CharField(max_length=10, verbose_name='資本金')),
                ('business_bank', models.TextField(verbose_name='取引銀行')),
                ('accounting_period', models.CharField(max_length=10, verbose_name='決算期')),
            ],
            options={
                'verbose_name': 'company (会社)',
                'verbose_name_plural': 'company (会社)',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('name', models.CharField(max_length=128, verbose_name='氏名')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': 'inquiry (問合せ)',
                'verbose_name_plural': 'inquiry (問合せ)',
                'db_table': 'inquiry',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('disp_flag', models.BooleanField(default=True, verbose_name='表示フラグ')),
            ],
            options={
                'verbose_name': 'news (ニュース)',
                'verbose_name_plural': 'news (ニュース)',
                'db_table': 'news',
            },
        ),
    ]
