# Generated by Django 4.1.2 on 2023-02-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='corporate_number',
            field=models.CharField(max_length=15, null=True, verbose_name='法人番号'),
        ),
    ]
