# Generated by Django 4.1.2 on 2023-02-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0002_company_corporate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='タイトル')),
                ('url', models.URLField(verbose_name='サイトURL')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('disp_flag', models.BooleanField(default=True, verbose_name='表示フラグ')),
            ],
            options={
                'verbose_name': 'sitelink (サイトリンク)',
                'verbose_name_plural': 'sitelink (サイトリンク)',
                'db_table': 'sitelink',
            },
        ),
    ]
