# Generated by Django 4.1 on 2023-03-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hp", "0003_sitelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="confirm_flag",
            field=models.BooleanField(default=False, verbose_name="確認完了フラグ"),
        ),
    ]
