# Generated by Django 4.1.1 on 2023-07-22 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hp", "0004_inquiry_confirm_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="entry_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="登録日"
            ),
        ),
    ]
